config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  get 'home/index'

  get 'tse/apuracao'

  resources :polling_places do
    collection do
      get "by_city"
      get "dashboard"
    end
    member do
      get "set_phone"
    end
  end
  resources :fiscal_publics do
    collection do
      get "autorizar"
    end
  end
  resources :regions
  resources :sections
  resources :cities
  resources :zones
  resources :notifications do
    collection do
      post "receber"
      get "ler"
    end

  end

  resources :partners do
    collection do
      get "aparelhos"
      get "novo_aparelho"
      get "ativar_aparelho"
      get "manual"
      get "youtubeVideo"
      get "ativar_fiscal"
      get "retornaParceiros"
      get "verificar_fiscal"
      get "verificar_fiscal_publico"
      get "termos_condicoes"
      get "set_polling_place"
      get "teste"
      get "atualiza_fiscal"
      get "location"
    end
  end
  devise_for :users
  resources :users
  resources :litigations
  resources :votes
  resources :bulletins
  resources :candidates
  resources :offices do
    collection do
      get "receber"
      get "teste"
    end
    member do
      get "apuracao"
    end
  end

  devise_scope :user do
    authenticated :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/processos'
    end
  end

  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/fiscal_public.rb
# == Schema Information
#
# Table name: fiscal_publics
#
#  id         :integer          not null, primary key
#  email      :string
#  name       :string
#  phone      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class FiscalPublic < ApplicationRecord
	has_many :envio_publics, dependent: :destroy
end

app/controllers/fiscal_publics_controller.rb
class FiscalPublicsController < ApplicationController
  before_action :authenticate_user!, except: :autorizar
  load_and_authorize_resource except: :autorizar
  before_action :set_fiscal_public, only: [:show, :edit, :update, :destroy]
  before_action :allow_iframe, :set_headers

  def set_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'GET'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
  end

  def autorizar
    fiscal = FiscalPublic.find_or_create_by(phone: params[:phone])
    fiscal.name = params[:name]
    fiscal.email = params[:email]
    fiscal.save
    render json: {msg: "ok", codigo: "fiscalpublico", fiscal: fiscal.id}
  end

  def allow_iframe
    response.headers.except! 'X-Frame-Options'
  end

  # GET /fiscal_publics
  # GET /fiscal_publics.json
  def index
    @fiscal_publics = FiscalPublic.all
  end

  # GET /fiscal_publics/1
  # GET /fiscal_publics/1.json
  def show
  end

  # GET /fiscal_publics/new
  def new
    @fiscal_public = FiscalPublic.new
  end

  # GET /fiscal_publics/1/edit
  def edit
  end

  # POST /fiscal_publics
  # POST /fiscal_publics.json
  def create
    @fiscal_public = FiscalPublic.new(fiscal_public_params)

    respond_to do |format|
      if @fiscal_public.save
        format.html { redirect_to @fiscal_public, notice: 'Fiscal public was successfully created.' }
        format.json { render :show, status: :created, location: @fiscal_public }
      else
        format.html { render :new }
        format.json { render json: @fiscal_public.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fiscal_publics/1
  # PATCH/PUT /fiscal_publics/1.json
  def update
    respond_to do |format|
      if @fiscal_public.update(fiscal_public_params)
        format.html { redirect_to @fiscal_public, notice: 'Fiscal public was successfully updated.' }
        format.json { render :show, status: :ok, location: @fiscal_public }
      else
        format.html { render :edit }
        format.json { render json: @fiscal_public.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fiscal_publics/1
  # DELETE /fiscal_publics/1.json
  def destroy
    @fiscal_public.destroy
    respond_to do |format|
      format.html { redirect_to fiscal_publics_url, notice: 'Fiscal public was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fiscal_public
      @fiscal_public = FiscalPublic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fiscal_public_params
      params.require(:fiscal_public).permit(:name, :phone, :email)
    end
end

app/helpers/fiscal_publics_helper.rb
module FiscalPublicsHelper
end

app/views/fiscal_publics/_form.html.erb
<%= form_for(fiscal_public) do |f| %>
  <% if fiscal_public.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fiscal_public.errors.count, "error") %> prohibited this fiscal_public from being saved:</h2>

      <ul>
      <% fiscal_public.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fiscal_publics/edit.html.erb
<h1>Editing Fiscal Public</h1>

<%= render 'form', fiscal_public: @fiscal_public %>

<%= link_to 'Show', @fiscal_public %> |
<%= link_to 'Back', fiscal_publics_path %>

app/views/fiscal_publics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fiscal Publics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fiscal_publics.each do |fiscal_public| %>
      <tr>
        <td><%= fiscal_public.name %></td>
        <td><%= fiscal_public.phone %></td>
        <td><%= fiscal_public.email %></td>
        <td><%= link_to 'Show', fiscal_public %></td>
        <td><%= link_to 'Edit', edit_fiscal_public_path(fiscal_public) %></td>
        <td><%= link_to 'Destroy', fiscal_public, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fiscal Public', new_fiscal_public_path %>

app/views/fiscal_publics/new.html.erb
<h1>New Fiscal Public</h1>

<%= render 'form', fiscal_public: @fiscal_public %>

<%= link_to 'Back', fiscal_publics_path %>

app/views/fiscal_publics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fiscal_public.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @fiscal_public.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @fiscal_public.email %>
</p>

<%= link_to 'Edit', edit_fiscal_public_path(@fiscal_public) %> |
<%= link_to 'Back', fiscal_publics_path %>