config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  get 'home/index'

  get 'tse/apuracao'

  resources :polling_places do
    collection do
      get "by_city"
      get "dashboard"
    end
    member do
      get "set_phone"
    end
  end
  resources :fiscal_publics do
    collection do
      get "autorizar"
    end
  end
  resources :regions
  resources :sections
  resources :cities
  resources :zones
  resources :notifications do
    collection do
      post "receber"
      get "ler"
    end

  end

  resources :partners do
    collection do
      get "aparelhos"
      get "novo_aparelho"
      get "ativar_aparelho"
      get "manual"
      get "youtubeVideo"
      get "ativar_fiscal"
      get "retornaParceiros"
      get "verificar_fiscal"
      get "verificar_fiscal_publico"
      get "termos_condicoes"
      get "set_polling_place"
      get "teste"
      get "atualiza_fiscal"
      get "location"
    end
  end
  devise_for :users
  resources :users
  resources :litigations
  resources :votes
  resources :bulletins
  resources :candidates
  resources :offices do
    collection do
      get "receber"
      get "teste"
    end
    member do
      get "apuracao"
    end
  end

  devise_scope :user do
    authenticated :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/processos'
    end
  end

  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/office.rb
# == Schema Information
#
# Table name: offices
#
#  id         :integer          not null, primary key
#  brancos    :integer
#  legenda    :integer
#  name       :string
#  nominais   :integer
#  nulos      :integer
#  numero     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Office < ApplicationRecord
  has_many :candidates
  has_many :votes
  has_many :office_cities
  has_many :cities, through: :office_cities

  def to_s
    self.numero.to_s
  end

  def votos_computados
    (brancos || 0) + (nominais || 0) + (nulos || 0)
  end

  def as_json(options = {})
    s = super(options)
    s[:candidatos] = self.candidates.order(votos: :desc)
    s[:pleito] = Litigation.last
    s[:votos_computados] = self.votos_computados
    s[:cidades] = JSON.parse(self.office_cities.to_json)
    s
  end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :authenticate_user!, except: :receber
  load_and_authorize_resource except: :receber
  before_action :allow_iframe, :set_headers
  before_action :set_office, only: [:show, :edit, :update, :destroy,:apuracao]

  def set_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'GET'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
  end

  def allow_iframe
    response.headers.except! 'X-Frame-Options'
  end

  # GET /offices
  # GET /offices.json
  def index
    @offices = Office.all
    #@dados_suplementares = Litigation.getDados
  end

  def apuracao_old
    @votes = @office.votes
    @candidatos = Candidate.order(votos: :desc)
    @eleito = false
    @segundoturno = false
    @pleito = Litigation.last
    @p = 0
    if @candidatos

      @p = (@pleito.eleitores - ( @office.brancos + @office.nulos + @pleito.faltantes))/2
      if @candidatos.first.votos >= @p + 1
        @eleito = true
      end
      #verifica se haverá segundo turno
      votos = @candidatos.sum{|a| a.votos} - @candidatos.first.votos
      if votos >= @p + 1
        @segundoturno = true
      end

    end
  end

  def apuracao
    render "firebase"
  end

  # GET /offices/1
  # GET /offices/1.json
  def show
  end

  def is_number?(string)
    true if Integer(string) rescue false
  end

  def receber_old
    dados = params[:data].split(" ")
    office = nil
    candidate = nil

    boletim = Bulletin.find_by_assinatura(dados.last.split(":")[1])

    if !boletim
      Bulletin.create(dados: params[:data], assinatura: dados.last.split(":")[1])

      dados.each do |d|
        if d.split(":")[0] == "CARG" #cargo
          office = Office.find_or_create_by(numero: d.split(":")[1].to_i)
        end
        if is_number?(d.split(":")[0])#candidato
          candidate = Candidate.find_or_create_by(numero: d.split(":")[0].to_i )
          candidate.office = office
          begin
            candidate.votos += d.split(":")[1].to_i
          rescue
            candidate.votos = d.split(":")[1].to_i
          end

          candidate.save
        end
        if d.split(":")[0] == "NOMI" #votos nominais
          begin
            office.nominais += d.split(":")[1].to_i
          rescue
            office.nominais = d.split(":")[1].to_i
          end

        end
        if d.split(":")[0] == "BRAN" #votos brancos
          begin
            office.brancos += d.split(":")[1].to_i
          rescue
            office.brancos = d.split(":")[1].to_i
          end

        end
        if d.split(":")[0] == "LEGC" #votos legenda
          begin
            office.legenda += d.split(":")[1].to_i
          rescue
            office.legenda = d.split(":")[1].to_i
          end

        end
        if d.split(":")[0] == "NULO" #votos nulos
          begin
            office.nulos += d.split(":")[1].to_i
          rescue
            office.nulos = d.split(":")[1].to_i
          end

          office.save
        end
      end
    else

    end

    render json: {ok: "OK"}
  end

  def receber

    #boletins = JSON.parse(params[:data])
    #binding.pry
    LerBoletimJob.perform_later(params[:data],params[:tipo],params[:idFiscal])
    render json: {ok: "OK"}
  end

  # GET /offices/new
  def new
    @office = Office.new
  end

  # GET /offices/1/edit
  def edit
  end

  # POST /offices
  # POST /offices.json
  def create
    @office = Office.new(office_params)

    respond_to do |format|
      if @office.save
        format.html { redirect_to @office, notice: 'Office was successfully created.' }
        format.json { render :show, status: :created, location: @office }
      else
        format.html { render :new }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offices/1
  # PATCH/PUT /offices/1.json
  def update
    respond_to do |format|
      if @office.update(office_params)
        format.html { redirect_to @office, notice: 'Office was successfully updated.' }
        format.json { render :show, status: :ok, location: @office }
      else
        format.html { render :edit }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    @office.destroy
    respond_to do |format|
      format.html { redirect_to offices_url, notice: 'Office was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office
      @office = Office.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def office_params
      params.require(:office).permit(:numero, :nominais, :brancos, :nulos, :legenda, :name)
    end
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/_form.html.erb
<%= form_for(office) do |f| %>
  <% if office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(office.errors.count, "error") %> prohibited this office from being saved:</h2>

      <ul>
      <% office.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="input-field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

  <div class="input-field">
    <%= f.label :numero %>
    <%= f.number_field :numero %>
  </div>

  <div class="input-field">
    <%= f.label :nominais %>
    <%= f.number_field :nominais %>
  </div>

  <div class="input-field">
    <%= f.label :brancos %>
    <%= f.number_field :brancos %>
  </div>

  <div class="input-field">
    <%= f.label :nulos %>
    <%= f.number_field :nulos %>
  </div>

  <div class="actions">
    <%= f.submit "Salvar", class:"btn" %>
  </div>
<% end %>

app/views/offices/apuracao.html.erb
<div class="row">
  <div class="col s12 m6 l3">
    <div class="card">
      <div class="card-content cyan white-text">
        <p class="card-stats-title">
          <i class="material-icons">person_outline</i> Nominais</p>
        <h4 class="card-stats-number"><%= @office.nominais %></h4>
        <!--<p class="card-stats-compare">
          <i class="material-icons">keyboard_arrow_up</i> 15%
          <span class="cyan text text-lighten-5">from yesterday</span>
        </p>-->
      </div>

    </div>
  </div>

  <div class="col s12 m6 l3">
    <div class="card">
      <div class="card-content deep-orange accent-2 white-text">
        <p class="card-stats-title">
          <i class="material-icons">content_copy</i> Brancos</p>
        <h4 class="card-stats-number"><%= @office.brancos %></h4>

      </div>

    </div>
  </div>
  <div class="col s12 m6 l3">
    <div class="card">
      <div class="card-content red accent-2 white-text">
        <p class="card-stats-title">
          <i class="material-icons">not_interested</i>Nulos</p>
        <h4 class="card-stats-number"><%= @office.nulos %></h4>

      </div>

    </div>
  </div>
  <div class="col s12 m6 l3">
    <div class="card">
      <div class="card-content blue accent-2 white-text">
        <p class="card-stats-title">
          <i class="material-icons">info</i>Restam</p>
        <h4 class="card-stats-number"><%= @pleito.votos_validos - @office.votos_computados %></h4>

      </div>

    </div>
  </div>
</div>


<div class="row">

  <div class="col s12 l6">
    <div class="card-panel">
      <h4 class="header2">Votos</h4>

      <div id="chart_div" class="center"></div>
    </div>
  </div>
  <div class="col s12 l6">
    <div class="card-panel">
      <h4 class="header2">Votos</h4>

      <div id="chart_collum" class="center"></div>
    </div>
  </div>
</div>
<% if @eleito %>
<div class="row">
  <div class="col s12">
      <div class="card">
        <h1>Candidato Eleito</h1>
      </div>
  </div>

      <div class="col s12 m6 l6">
        <div class="card horizontal">
          <div class="card-image">
            <img src="<%= @candidatos.first.foto.url %>">
          </div>
          <div class="card-stacked">
            <div class="card-content">
              <h4><%= @candidatos.first.name %></h4>
              <h1><%= @candidatos.first.votos %></h1>
            </div>
          </div>
        </div>
      </div>
</div>
<% else %>
<div class="row">

      <div class="col s12">
        <div class="card">
          <h1><%= @segundoturno == true ? "Segundo Turno Confirmado" : "Apuração em andamento" %></h1>
        </div>
      </div>
      <div class="col s12 m6 l6">
        <div class="card horizontal">
          <div class="card-image">
            <img src="<%= @candidatos.first.foto.url %>">
          </div>
          <div class="card-stacked">
            <div class="card-content">
              <h4><%= @candidatos.first.name %></h4>
              <h1><%= @candidatos.first.votos %><%= "/#{(@p+1) - @candidatos.first.votos}" if !@segundoturno%></h1>
            </div>


          </div>
        </div>
      </div>
      <div class="col s12 m6 l6">
        <div class="card horizontal">
          <div class="card-image">
            <img src="<%= @candidatos.second.foto.url %>">
          </div>
          <div class="card-stacked">
            <div class="card-content">
              <h4><%= @candidatos.second.name %></h4>
              <h1><%= @candidatos.second.votos %></h1>
            </div>

          </div>
        </div>
      </div>

<% end %>
</div>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">

    // Load the Visualization API and the corechart package.
    google.charts.load('current', {'packages':['corechart']});

    // Set a callback to run when the Google Visualization API is loaded.
    google.charts.setOnLoadCallback(drawChart);

    // Callback that creates and populates a data table,
    // instantiates the pie chart, passes in the data and
    // draws it.
    function drawChart() {
        var dados = <%= @votes.group_by(&:candidato).map{|candidato, votes| [Candidate.find_by_numero(candidato).name,votes.sum{|a| a.votos}]}.to_s.html_safe %>;
        dados.unshift(["Candidato","Votos"]);
        console.log(dados);
        var data = google.visualization.arrayToDataTable(dados);

        var options = {
            title: 'Votos Nominais',
            'width':400,
            'height':300
        };

        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));

        chart.draw(data, options);

        var options_collum = {
            title: 'Votos Nominais'
        };

        var chart_collum = new google.visualization.ColumnChart(document.getElementById('chart_collum'));

        chart.draw(data, options);
        chart_collum.draw(data, options_collum);
    }
</script>

app/views/offices/edit.html.erb
<h1>Editando Cargo</h1>

<%= render 'form', office: @office %>


<%= link_to 'Voltar', offices_path, target:"_self" %>

app/views/offices/firebase.html.erb
<div ng-controller="firebase_controller" ng-init="cargo = 'cargo_<%= @office.id %>' ">
  <div class="row">
    <div class="col s12 m6 l3">
      <div class="card">
        <div class="card-content cyan white-text">
          <p class="card-stats-title">
            <i class="material-icons">person_outline</i> Nominais</p>
          <h4 class="card-stats-number"> {{data.apuracao[cargo].nominais}}</h4>
          <!--<p class="card-stats-compare">
            <i class="material-icons">keyboard_arrow_up</i> 15%
            <span class="cyan text text-lighten-5">from yesterday</span>
          </p>-->
        </div>

      </div>
    </div>

    <div class="col s12 m6 l3">
      <div class="card">
        <div class="card-content deep-orange accent-2 white-text">
          <p class="card-stats-title">
            <i class="material-icons">content_copy</i> Brancos</p>
          <h4 class="card-stats-number">{{data.apuracao[cargo].brancos}}</h4>

        </div>

      </div>
    </div>
    <div class="col s12 m6 l3">
      <div class="card">
        <div class="card-content red accent-2 white-text">
          <p class="card-stats-title">
            <i class="material-icons">not_interested</i>Nulos</p>
          <h4 class="card-stats-number">{{data.apuracao[cargo].nulos}}</h4>

        </div>

      </div>
    </div>
    <div class="col s12 m6 l3">
      <div class="card">
        <div class="card-content blue accent-2 white-text">
          <p class="card-stats-title">
            <i class="material-icons">info</i>Restam</p>
          <h4 class="card-stats-number">{{data.apuracao[cargo].pleito.eleitores - data.apuracao[cargo].pleito.faltantes - data.apuracao[cargo].votos_computados}}</h4>

        </div>

      </div>
    </div>
  </div>

  <div id="card-alert" class="card gradient-45deg-purple-deep-orange" ng-if="eleito">
    <div class="card-content white-text">
      <i class="material-icons">notifications</i> ELEIÇÃO MATEMÁTICAMENTE DEFINIDA! O candidato {{data.apuracao[cargo].candidatos[0].name}} já está matemáticamente eleito.<p></p>
    </div>
  </div>

  <div id="card-alert" class="card gradient-45deg-purple-deep-orange" ng-if="segundoturno">
    <div class="card-content white-text">
      <i class="material-icons">notifications</i> ELEIÇÃO MATEMÁTICAMENTE DEFINIDA! Os candidatos {{data.apuracao[cargo].candidatos[0].name}} e {{data.apuracao[cargo].candidatos[1].name}} estão no segundo turno no momento. Matemáticamente não é mais possível eleição em primeiro turno<p></p>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <div class="row">
        <div class="col s12 m4">
          <div class="card">
            <div class="card-image">
              <img src="{{data.apuracao[cargo].candidatos[0].foto.url || '/nobody.jpg'}}">
              <a class="btn-floating halfway-fab waves-effect waves-light blue left">
                <i>1º</i>
              </a>
              <span class="new badge lime darken-1" data-badge-caption="Candidato Eleito" ng-if="eleito"> </span>
              <span class="new badge  light-blue darken-4" data-badge-caption="Segundo Turno" ng-if="segundoturno"> </span>
            </div>
            <div class="card-content">
              <h5 class="center font-weight-400">{{data.apuracao[cargo].candidatos[0].name}}</h5>
              <div class="divider mt-5"></div>
              <div class="col l6 m6 s6 padding-5">
                <p class="center">
                  <b>{{data.apuracao[cargo].candidatos[0].votos}}</b>
                </p>
                <p class="center">votos</p>
              </div>
              <div class="col l6 m6 s6 padding-5" ng-if="!eleito">
                <p class="center">
                  <b>{{arredondar((metade+1) - data.apuracao[cargo].candidatos[0].votos)}}</b>
                </p>
                <p class="center">para ser eleito</p>
              </div>
            </div>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="card">
            <div class="card-image">
              <img src="{{data.apuracao[cargo].candidatos[1].foto.url || '/nobody.jpg'}}">
              <a class="btn-floating halfway-fab waves-effect waves-light blue left">
                <i>2º</i>
              </a>
              <span class="new badge red darken-4" data-badge-caption="Fora da Disputa" ng-if="eleito"> </span>
              <span class="new badge  light-blue darken-4" data-badge-caption="Segundo Turno" ng-if="segundoturno"> </span>
            </div>
            <div class="card-content">
              <h5 class="center font-weight-400">{{data.apuracao[cargo].candidatos[1].name}}</h5>
              <div class="divider mt-5"></div>
              <div class="col l6 m6 s6 padding-5">
                <p class="center">
                  <b>{{data.apuracao[cargo].candidatos[1].votos}}</b>
                </p>
                <p class="center">votos</p>
              </div>
              <div class="col l6 m6 s6 padding-5" ng-if="!eleito && !segundoturno">
                <p class="center">
                  <b>{{arredondar((metade+1) - data.apuracao[cargo].candidatos[1].votos)}}</b>
                </p>
                <p class="center">para ser eleito</p>
              </div>
            </div>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="card">
            <div class="card-image">
              <img src="{{data.apuracao[cargo].candidatos[2].foto.url || '/nobody.jpg'}}">
              <a class="btn-floating halfway-fab waves-effect waves-light blue left">
                <i>3º</i>
              </a>
              <span class="new badge red darken-4" data-badge-caption="Fora da Disputa" ng-if="eleito || segundoturno"> </span>
            </div>
            <div class="card-content">
              <h5 class="center font-weight-400">{{data.apuracao[cargo].candidatos[2].name}}</h5>
              <div class="divider mt-5"></div>
              <div class="col l6 m6 s6 padding-5">
                <p class="center">
                  <b>{{data.apuracao[cargo].candidatos[2].votos}}</b>
                </p>
                <p class="center">votos</p>
              </div>
              <div class="col l6 m6 s6 padding-5" ng-if="!eleito && !segundoturno">
                <p class="center">
                  <b>{{arredondar((metade+1) - data.apuracao[cargo].candidatos[2].votos)}}</b>
                </p>
                <p class="center">para ser eleito</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>



  <div class="row">
    <div class="col s12 m6">
      <div class="card-panel">
        <table>
          <thead>
          <th>Candidato</th>
          <th>Votos</th>
          <th>Percentual</th>
          </thead>
          <tbody>
          <tr ng-repeat="candidato in data.apuracao[cargo].candidatos">
            <td>{{candidato.name}}</td>
            <td>{{candidato.votos}}</td>
            <td>{{(candidato.votos * 100)/data.apuracao[cargo].nominais | number:2}}%</td>
          </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="col s12 m6">
      <div class="card-panel">
        <h4 class="header2">Votos</h4>

        <div id="chart_div" class="center"></div>
      </div>
    </div>
    <div class="col s12">
      <div class="card-panel">
        <h4 class="header2">Votos</h4>

        <div id="chart_collum" class="center"></div>
      </div>
    </div>

  </div>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">

    // Load the Visualization API and the corechart package.
    google.charts.load('current', {'packages':['corechart']});

    // Set a callback to run when the Google Visualization API is loaded.
    //google.charts.setOnLoadCallback(drawChart);

    // Callback that creates and populates a data table,
    // instantiates the pie chart, passes in the data and
    // draws it.
    function drawChart(dados) {
        var dados = dados;
        dados.unshift(["Candidato","Votos"]);
        console.log(dados);
        var data = google.visualization.arrayToDataTable(dados);

        var options = {
            title: 'Votos Nominais',
            'width':400,
            'height':300
        };

        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));

        chart.draw(data, options);

        var options_collum = {
            title: 'Votos Nominais'
        };

        var chart_collum = new google.visualization.ColumnChart(document.getElementById('chart_collum'));

        chart.draw(data, options);
        chart_collum.draw(data, options_collum);
    }
</script>
  <script type="text/javascript" charset="utf-8">
      setTimeout( function () {
          swal("Atualização Automática", "Na TagHere você não precisa ficar atualizando a página toda hora, os dados são atualizados automáticamente assim que disponíveis! :)", "info")

      }, 1000)
  </script>

app/views/offices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cargos</h1>

<table>
  <thead>
    <tr>
      <th>Cargo</th>
      <th>Nominais</th>
      <th>Brancos</th>
      <th>Legenda</th>
      <th>Nulos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offices.each do |office| %>
      <tr>
        <td><%= office.name %></td>
        <td><%= office.nominais %></td>
        <td><%= office.brancos %></td>
        <td><%= office.legenda %></td>
        <td><%= office.nulos %></td>
        <td><%= link_to "Apuração", apuracao_office_path(office), target:"_self"%></td>
        <% if current_user.admin? %>
        <td><%= link_to 'Visualizar', office, target:"_self" %></td>
        <td><%= link_to 'Editar', edit_office_path(office), target:"_self" %></td>
        <td><%= link_to 'Deletar', office, method: :delete, data: { confirm: 'Are you sure?' }, target:"_self" %></td>
            <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Cargo', new_office_path if current_user.admin?%>

<!-- "#{@dados_suplementares["processoEleitoral"]["eleicoes"][0]["partidosPorCargos"].map{|a| a["cargo"]["codigo"].to_i == office.numero ? a["cargo"]["nomeNeutro"] : office.numero}.first}" -->

app/views/offices/new.html.erb
<h1>Novo Cargo</h1>

<%= render 'form', office: @office %>

<%= link_to 'Voltar', offices_path, target:"_self" %>

app/views/offices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numero:</strong>
  <%= @office.numero %>
</p>

<p>
  <strong>Nominais:</strong>
  <%= @office.nominais %>
</p>

<p>
  <strong>Brancos:</strong>
  <%= @office.brancos %>
</p>

<p>
  <strong>Nulos:</strong>
  <%= @office.nulos %>
</p>

<%= link_to 'Edit', edit_office_path(@office) %> |
<%= link_to 'Back', offices_path %>