config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  get 'home/index'

  get 'tse/apuracao'

  resources :polling_places do
    collection do
      get "by_city"
      get "dashboard"
    end
    member do
      get "set_phone"
    end
  end
  resources :fiscal_publics do
    collection do
      get "autorizar"
    end
  end
  resources :regions
  resources :sections
  resources :cities
  resources :zones
  resources :notifications do
    collection do
      post "receber"
      get "ler"
    end

  end

  resources :partners do
    collection do
      get "aparelhos"
      get "novo_aparelho"
      get "ativar_aparelho"
      get "manual"
      get "youtubeVideo"
      get "ativar_fiscal"
      get "retornaParceiros"
      get "verificar_fiscal"
      get "verificar_fiscal_publico"
      get "termos_condicoes"
      get "set_polling_place"
      get "teste"
      get "atualiza_fiscal"
      get "location"
    end
  end
  devise_for :users
  resources :users
  resources :litigations
  resources :votes
  resources :bulletins
  resources :candidates
  resources :offices do
    collection do
      get "receber"
      get "teste"
    end
    member do
      get "apuracao"
    end
  end

  devise_scope :user do
    authenticated :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/processos'
    end
  end

  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/region.rb
# == Schema Information
#
# Table name: regions
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  partner_id :integer
#
# Indexes
#
#  index_regions_on_partner_id  (partner_id)
#
# Foreign Keys
#
#  fk_rails_...  (partner_id => partners.id)
#

class Region < ApplicationRecord
  belongs_to :partner
  has_one :candidate, through: :partner
  has_many :region_cities
  has_many :cities, through: :region_cities

  accepts_nested_attributes_for :region_cities, allow_destroy: true
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: [:show, :edit, :update, :destroy]

  # GET /regions
  # GET /regions.json
  def index
    if current_user.admin?
      @regions = Region.all
    elsif current_user.partner?
      @regions = Region.where(partner: current_user.partner)
    end

  end

  # GET /regions/1
  # GET /regions/1.json
  def show
    @candidato = @region.candidate
    @votos = @candidato.votes.where(city_id: @region.city_ids)
  end

  # GET /regions/new
  def new
    @region = Region.new(partner: current_user.partner)
  end

  # GET /regions/1/edit
  def edit
  end

  # POST /regions
  # POST /regions.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to @region, notice: 'Region was successfully created.' }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1
  # PATCH/PUT /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to @region, notice: 'Region was successfully updated.' }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1
  # DELETE /regions/1.json
  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to regions_url, notice: 'Region was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def region_params
      params.require(:region).permit(:name, :partner_id,region_cities_attributes:[:id,:region_id,:city_id,:_destroy])
    end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/regions/_form.html.erb
<%= nested_form_for(region) do |f| %>
  <% if region.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(region.errors.count, "error") %> prohibited this region from being saved:</h2>

      <ul>
      <% region.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="card">
  <div class="card-content">
  <div class="field">
    <%= f.label :name, "Nome" %>
    <%= f.text_field :name %>
  </div>


  <% if current_user.partner? %>
    <%= f.hidden_field :partner_id %>
  <% else %>
        <div class="input-field">
          <%= f.select :partner_id, Partner.all.map{|a| [a.name,a.id]},{prompt: true} %>
          <%= f.label :partner_id, "Parceiro" %>
        </div>
  <% end %>

    <div class="card" style="overflow: visible;">
      <div class="card-content">
        <span class="card-title">Municípios</span>
        <%= f.fields_for :region_cities do |l| %>
            <div class="row">
              <div class="input col s8">
                <%= f.label :city_id, "Município" %>
                <%= l.select :city_id, City.all.map{|a| [a.name, a.id]},{prompt:true},{class:"select2 browser-default"}%>


              </div>
              <div class="col s2 pull-left">
                <%= l.link_to_remove "Remover", class:"glyphicon glyphicon-remove"%>
              </div>
            </div>
            <script>
                $(document).ready(function(){
                    $('.select2').select2();

                })
            </script>
        <% end %>
        <p><%= f.link_to_add "Inserir Município", :region_cities %></p>

      </div>
    </div>
  </div>
</div>
  <div class="actions">
    <%= f.submit "Salvar", class:"btn", target:"_self" %>
  </div>
<% end %>

app/views/regions/edit.html.erb
<h1>Editing Region</h1>

<%= render 'form', region: @region %>

<%= link_to 'Show', @region %> |
<%= link_to 'Back', regions_path %>

app/views/regions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Regiões</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <% if current_user.admin? %>
        <th>Parceiro</th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @regions.each do |region| %>
      <tr>
        <td><%= region.name %></td>
        <% if current_user.admin? %>
          <td><%= region.partner %></td>
        <% end %>
        <td><%= link_to 'Visualizar', region %></td>
        <td><%= link_to 'Editar', edit_region_path(region) %></td>
        <td><%= link_to 'Deletar', region, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Região', new_region_path, class: "btn", target:"_self" %>

app/views/regions/new.html.erb
<h1>Nova Região</h1>

<%= render 'form', region: @region %>

<%= link_to 'Voltar', regions_path, target:"_self" %>

app/views/regions/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <div class="card-content">
    <p>
      <strong>Região:</strong>
      <%= @region.name %>
    </p>
    

    <div id="chart_collum" class="center"></div>
    <div id="chart_div" class="center"></div>
  </div>
</div>


<%= link_to 'Editar', edit_region_path(@region), target:"_self" %> |
<%= link_to 'Voltar', regions_path, target:"_self" %>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">

    // Load the Visualization API and the corechart package.
    google.charts.load('current', {'packages':['corechart']});

    // Set a callback to run when the Google Visualization API is loaded.
    google.charts.setOnLoadCallback(drawChart);

    // Callback that creates and populates a data table,
    // instantiates the pie chart, passes in the data and
    // draws it.
    function drawChart() {
        var dados = <%= @votos.group_by(&:city).map{|city, votos| [city.name,votos.sum{|a| a.votos}]}.to_s.html_safe %>;
        dados.unshift(["Cidade","Votos"]);
        console.log(dados);
        var data = google.visualization.arrayToDataTable(dados);

        var options = {
            title: 'Votos Nominais',
            'width':400,
            'height':300
        };

        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));

        chart.draw(data, options);

        var options_collum = {
            title: 'Votos Nominais'
        };

        var chart_collum = new google.visualization.ColumnChart(document.getElementById('chart_collum'));

        chart.draw(data, options);
        chart_collum.draw(data, options_collum);
    }
</script>